apiVersion: v1
kind: Service
metadata:
  name: busolag-prod-service
  namespace: busolag-prod
spec:
  selector:
    app: busolag-prod
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  type: LoadBalancer